export const LIST_WEATHER = 'LIST_WEATHER';
export const CITIES_SEARCH = 'CITIES_SEARCH';
export const CITIES_NULL = 'CITIES_NULL';
export const SEARCH_VALUE = 'SEARCH_VALUE';
export const GEOLOCATION = 'GEOLOCATION';
